# Inhalte der Leistungsseiten (München). Wird von tools/leistungsseiten-bauen.py gelesen.
# Texte hier ändern und danach `python3 tools/leistungsseiten-bauen.py` ausführen.

LEISTUNGEN = [
    {
        "slug": "treppenhausreinigung",
        "datei": "treppenhausreinigung-muenchen.html",
        "name": "Treppenhausreinigung",
        "icon": "i-stairs",
        "title": "Treppenhausreinigung München – zuverlässig & regelmäßig | CD Reinigungsservice",
        "description": "Treppenhausreinigung in München für Hausverwaltungen, Eigentümer und Mieter: regelmäßig, gründlich und mit festem Ansprechpartner. Jetzt unverbindlich anfragen.",
        "h1": "Treppenhausreinigung in München",
        "lead": "Saubere Treppenhäuser, Eingänge und Flure – regelmäßig, gründlich und nach festem Plan.",
        "text": [
            "Das Treppenhaus ist die Visitenkarte eines Hauses. Hier begegnen sich Mieter, Eigentümer, Besucher und Handwerker – und hier fällt Schmutz zuerst auf. Als Reinigungsfirma aus München übernehmen wir die Treppenhausreinigung für Mehrfamilienhäuser, Wohnanlagen und Geschäftshäuser im gesamten Stadtgebiet und im Umland.",
            "Wir reinigen in dem Rhythmus, der zu Ihrem Objekt passt: wöchentlich, vierzehntäglich oder monatlich. Dabei arbeiten wir nach einem festen Leistungsplan, damit Sie genau wissen, was wann erledigt wird. Hausverwaltungen profitieren von einem festen Ansprechpartner und kurzen Wegen – Rückfragen klären wir telefonisch, per E-Mail oder WhatsApp.",
            "Für die Bewohner bedeutet eine regelmäßige Treppenhausreinigung mehr als nur Optik: Gepflegte Böden halten länger, Handläufe und Lichtschalter werden hygienisch sauber gehalten, und Eingangsbereiche wirken einladend. Gerade in der nassen Jahreszeit, wenn Straßenschmutz und Streusalz ins Haus getragen werden, macht sich eine verlässliche Reinigung schnell bemerkbar.",
            "Sie möchten die Treppenhausreinigung von den Mietern auf einen Dienstleister übertragen oder suchen einen neuen, zuverlässigen Partner für Ihre Wohnanlage in München? Schildern Sie uns kurz Ihr Objekt – Anzahl der Etagen, Bodenbelag und gewünschte Häufigkeit – und wir erstellen Ihnen ein individuelles Angebot.",
        ],
        "warum": "Unser Standort liegt im Münchner Westen. Von dort aus betreuen wir Treppenhäuser in Aubing, Pasing, Laim und im gesamten Stadtgebiet. Sie haben mit Inhaber Eric Darko einen festen Ansprechpartner, der Ihr Objekt kennt. Wir arbeiten mit festen Reinigungstagen, damit die Bewohner wissen, wann gereinigt wird und die Böden trocknen können. Fällt Ihnen etwas auf, genügt ein kurzer Anruf oder eine WhatsApp-Nachricht – wir kümmern uns schnell darum. So bleibt Ihr Treppenhaus dauerhaft in einem gepflegten Zustand, ohne dass Sie sich selbst darum kümmern müssen.",
        "umfang": [
            "Kehren und feuchtes Wischen aller Treppenstufen, Podeste und Flure",
            "Reinigung von Handläufen, Geländern, Lichtschaltern und Türklinken",
            "Eingangsbereich, Hauseingangstür und Briefkastenanlage",
            "Fensterbänke und Heizkörper im Treppenhaus",
            "Aufzugskabine und Kellerabgänge nach Absprache",
            "Entfernen von Spinnweben und Beseitigung von Flecken",
        ],
        "faq": [
            ("Wie oft sollte ein Treppenhaus gereinigt werden?", "Für die meisten Mehrfamilienhäuser in München empfehlen wir eine wöchentliche Reinigung. Bei kleineren Häusern mit wenigen Parteien reicht oft ein Rhythmus von 14 Tagen. Wir beraten Sie gern, was für Ihr Objekt sinnvoll ist."),
            ("Kann die Treppenhausreinigung auf die Nebenkosten umgelegt werden?", "Ja, die Kosten einer regelmäßigen Treppenhausreinigung durch einen Dienstleister zählen in der Regel zu den umlagefähigen Betriebskosten. Wir stellen Ihnen dafür übersichtliche Rechnungen aus."),
            ("Arbeiten Sie auch für Hausverwaltungen?", "Ja. Wir betreuen Wohnanlagen im Auftrag von Hausverwaltungen und Eigentümergemeinschaften und sind für Rückfragen direkt erreichbar."),
            ("Wie bekomme ich ein Angebot?", "Nutzen Sie unser Anfrageformular oder rufen Sie uns an unter 0176 72883621. Wir melden uns innerhalb von 24 Stunden mit einem individuellen Angebot."),
        ],
    },
    {
        "slug": "bueroreinigung",
        "datei": "bueroreinigung-muenchen.html",
        "name": "Büroreinigung",
        "icon": "i-office",
        "title": "Büroreinigung München – für Büros & Praxen | CD Reinigungsservice",
        "description": "Büroreinigung in München: gepflegte Arbeitsplätze, Küchen und Sanitärbereiche – diskret, flexibel und nach Ihrem Zeitplan. Jetzt kostenloses Angebot anfragen.",
        "h1": "Büroreinigung in München",
        "lead": "Gepflegte Arbeitsplätze, Küchen und Sanitärräume – diskret und nach Ihrem Zeitplan.",
        "text": [
            "Ein sauberes Büro ist mehr als ein guter Eindruck bei Kunden: Es sorgt für ein angenehmes Arbeitsklima, weniger Krankheitstage und motivierte Mitarbeiter. CD Reinigungsservice übernimmt die Büroreinigung für Unternehmen, Agenturen, Kanzleien und Praxen in München – vom kleinen Einzelbüro bis zur kompletten Büroetage.",
            "Wir richten uns nach Ihrem Arbeitsalltag. Die Reinigung erfolgt auf Wunsch früh morgens, abends oder am Wochenende, damit Ihr Betrieb ungestört weiterlaufen kann. Gemeinsam legen wir fest, welche Räume wie oft gereinigt werden – täglich, mehrmals pro Woche oder wöchentlich. So zahlen Sie nur für das, was Sie wirklich brauchen.",
            "Besonders wichtig sind uns Hygiene und Diskretion. Teeküchen, Sanitärbereiche und häufig berührte Flächen wie Türklinken, Lichtschalter und Telefone reinigen wir gründlich. Mit vertraulichen Unterlagen und Ihrem Eigentum gehen wir selbstverständlich sorgfältig um.",
            "Sie suchen eine zuverlässige Büroreinigung in München oder möchten Ihren bisherigen Dienstleister wechseln? Teilen Sie uns kurz Größe, Raumaufteilung und gewünschte Reinigungszeiten mit. Wir erstellen Ihnen ein transparentes Angebot und stehen Ihnen als fester Ansprechpartner zur Verfügung.",
        ],
        "warum": "Als kleine Reinigungsfirma aus München arbeiten wir persönlich und flexibel. Sie sprechen direkt mit Inhaber Eric Darko, nicht mit einem Callcenter. Änderungen am Reinigungsplan, zusätzliche Termine vor einem wichtigen Kundenbesuch oder eine Sonderreinigung nach einer Veranstaltung lassen sich daher unkompliziert abstimmen. Wir setzen auf feste Abläufe und gründliche Arbeit, damit Sie sich jeden Morgen auf ein sauberes Büro verlassen können. Viele Kunden starten mit einer Grundreinigung und gehen danach in die regelmäßige Unterhaltsreinigung über.",
        "umfang": [
            "Staubsaugen und Wischen aller Bodenflächen",
            "Abstauben und feuchtes Reinigen von Schreibtischen und Ablagen",
            "Leeren der Papierkörbe und Mülltrennung",
            "Reinigung und Desinfektion von Sanitärräumen",
            "Teeküche: Spüle, Arbeitsflächen, Geräte außen, Spülmaschine",
            "Türklinken, Lichtschalter und Glastüren",
        ],
        "faq": [
            ("Wann findet die Büroreinigung statt?", "Ganz nach Ihrem Wunsch: früh morgens, abends nach Feierabend oder am Wochenende. So stört die Reinigung Ihren Arbeitsalltag nicht."),
            ("Wie oft sollte ein Büro gereinigt werden?", "Das hängt von der Anzahl der Mitarbeiter und dem Kundenverkehr ab. Viele Büros in München lassen zwei- bis dreimal pro Woche reinigen, Sanitärbereiche und Küchen häufiger. Wir beraten Sie gern."),
            ("Reinigen Sie auch Praxen und Ladenflächen?", "Ja, neben Büros reinigen wir auch Praxen, Kanzleien, Ladenflächen und andere Gewerberäume in München."),
            ("Was kostet eine Büroreinigung?", "Der Preis hängt von Fläche, Häufigkeit und Leistungsumfang ab. Nach Ihrer Anfrage erhalten Sie innerhalb von 24 Stunden ein individuelles, kostenloses Angebot."),
        ],
    },
    {
        "slug": "fensterreinigung",
        "datei": "fensterreinigung-muenchen.html",
        "name": "Fenster- & Glasreinigung",
        "icon": "i-window",
        "title": "Fensterreinigung & Glasreinigung München | CD Reinigungsservice",
        "description": "Fenster- und Glasreinigung in München für Privat und Gewerbe: streifenfreie Fenster, Rahmen, Glastüren und Schaufenster. Jetzt unverbindlich anfragen.",
        "h1": "Fenster- &amp; Glasreinigung in München",
        "lead": "Streifenfreie Fenster, saubere Rahmen und klare Glasflächen – für Wohnung, Büro und Laden.",
        "text": [
            "Saubere Fenster lassen mehr Licht in Ihre Räume und machen sofort einen gepflegten Eindruck. Gleichzeitig ist das Fensterputzen eine Aufgabe, die viel Zeit kostet und ohne die richtige Technik schnell Streifen hinterlässt. CD Reinigungsservice übernimmt die Fenster- und Glasreinigung in München für Privathaushalte, Büros, Praxen und Geschäfte.",
            "Wir reinigen Glasflächen innen und außen, inklusive Rahmen, Falze und Fensterbänke. Mit professionellen Abziehern und geeigneten Reinigungsmitteln sorgen wir für ein streifenfreies Ergebnis – auch bei großen Fensterfronten, Glastüren, Wintergärten oder Schaufenstern.",
            "Für Gewerbekunden in München ist eine regelmäßige Glasreinigung besonders wichtig: Schaufenster und Eingangstüren sind das Erste, was Kunden sehen. Wir bieten Ihnen dafür feste Intervalle, zum Beispiel monatlich oder vierteljährlich. Privatkunden buchen die Fensterreinigung häufig als Frühjahrs- oder Herbstputz oder nach einer Renovierung.",
            "Sagen Sie uns einfach, wie viele Fenster und welche Glasflächen gereinigt werden sollen und ob sie gut erreichbar sind. Wir erstellen Ihnen ein faires Angebot und vereinbaren einen Termin, der Ihnen passt.",
        ],
        "warum": "Viele Münchner Altbauten haben hohe Fenster, Doppelfenster oder Sprossen – hier ist Erfahrung gefragt. Wir nehmen uns die Zeit, die jedes Fenster braucht, und arbeiten sauber: Böden und Fensterbänke schützen wir, und nach der Reinigung hinterlassen wir keine Wasserflecken. Die Fensterreinigung lässt sich gut mit einer Grundreinigung oder der regelmäßigen Büroreinigung kombinieren. So sparen Sie Anfahrten und haben alles aus einer Hand. Als Ansprechpartner steht Ihnen Inhaber Eric Darko direkt zur Verfügung.",
        "umfang": [
            "Fensterscheiben innen und außen, streifenfrei",
            "Fensterrahmen, Falze und Dichtungen",
            "Fensterbänke innen und außen",
            "Glastüren, Trennwände und Glasgeländer",
            "Schaufenster und Eingangsbereiche von Geschäften",
            "Wintergärten und Balkonverglasungen nach Absprache",
        ],
        "faq": [
            ("Reinigen Sie auch die Fensterrahmen?", "Ja, bei unserer Fensterreinigung sind Rahmen, Falze und Fensterbänke standardmäßig enthalten."),
            ("Wie oft sollten Fenster gereinigt werden?", "Im Privathaushalt reichen meist zwei bis vier Reinigungen pro Jahr. Schaufenster und Eingangstüren von Geschäften sollten deutlich häufiger gereinigt werden, oft monatlich."),
            ("Muss ich bei der Fensterreinigung zu Hause sein?", "Für die Innenseiten benötigen wir Zugang zu den Räumen. Den genauen Ablauf stimmen wir vorher mit Ihnen ab."),
            ("Bieten Sie Glasreinigung auch für Firmen an?", "Ja, wir reinigen Glasflächen von Büros, Praxen und Läden in München – einmalig oder in festen Intervallen."),
        ],
    },
    {
        "slug": "winterdienst",
        "datei": "winterdienst-muenchen.html",
        "name": "Winterdienst",
        "icon": "i-snow",
        "title": "Winterdienst München – Schneeräumen & Streuen | CD Reinigungsservice",
        "description": "Winterdienst in München: Räumen und Streuen von Gehwegen, Zufahrten und Hauseingängen – zuverlässig auch früh am Morgen. Jetzt für die Saison anfragen.",
        "h1": "Winterdienst in München",
        "lead": "Räumen und Streuen von Gehwegen, Zufahrten und Eingängen – zuverlässig auch früh am Morgen.",
        "text": [
            "Wenn es in München schneit oder Glätte droht, müssen Gehwege und Zugänge rechtzeitig geräumt und gestreut werden. Für Eigentümer, Hausverwaltungen und Gewerbetreibende ist das eine Pflicht – und bei einem Unfall auf ungeräumten Wegen drohen Haftungsfragen. CD Reinigungsservice übernimmt den Winterdienst für Ihr Objekt, damit Sie sich darum nicht kümmern müssen.",
            "Wir räumen Schnee und streuen Gehwege, Hauseingänge, Zufahrten, Stellplätze und Mülltonnenplätze. Dabei achten wir auf die Zeiten, zu denen die Wege sicher begehbar sein müssen – also auch früh am Morgen, bevor Bewohner, Mitarbeiter oder Kunden unterwegs sind. Bei anhaltendem Schneefall oder erneuter Glätte kommen wir wieder.",
            "Am besten vereinbaren Sie den Winterdienst bereits im Herbst für die gesamte Saison. So ist Ihr Objekt fest eingeplant, und beim ersten Schnee ist alles geregelt. Die Einsätze dokumentieren wir auf Wunsch, damit Sie im Zweifel nachweisen können, dass Ihrer Räum- und Streupflicht nachgekommen wurde.",
            "Sie möchten den Winterdienst für ein Wohnhaus, eine Wohnanlage oder ein Firmengelände in München vergeben? Teilen Sie uns die Lage und die zu räumenden Flächen mit – wir erstellen Ihnen ein Angebot für die kommende Wintersaison.",
        ],
        "warum": "Wer in München einen Winterdienst beauftragt, braucht vor allem eines: Verlässlichkeit. Deshalb planen wir die Einsätze für unsere Winterdienst-Kunden fest ein und beobachten die Wetterlage. Wenn Schnee oder Glätte angekündigt ist, sind wir rechtzeitig vor Ort. Sie erreichen Inhaber Eric Darko direkt per Telefon oder WhatsApp, falls an Ihrem Objekt etwas nachgearbeitet werden muss. Auf Wunsch kombinieren wir den Winterdienst mit der Treppenhausreinigung, damit der Eingangsbereich auch bei Schneematsch sauber bleibt.",
        "umfang": [
            "Schneeräumen von Gehwegen und Hauseingängen",
            "Streuen bei Glätte und Glatteis",
            "Zufahrten, Stellplätze und Mülltonnenplätze",
            "Einsätze früh morgens und bei Bedarf mehrfach täglich",
            "Dokumentation der Einsätze auf Wunsch",
            "Saisonvertrag für die gesamte Wintersaison",
        ],
        "faq": [
            ("Ab wann sollte ich den Winterdienst buchen?", "Am besten im Herbst, bevor der erste Schnee fällt. Dann ist Ihr Objekt für die ganze Saison fest eingeplant."),
            ("Zu welchen Zeiten wird geräumt?", "Wir richten uns nach den Zeiten, zu denen die Wege in München sicher begehbar sein müssen, und räumen deshalb auch früh am Morgen. Bei erneutem Schneefall oder Glätte kommen wir wieder."),
            ("Übernehmen Sie die Räum- und Streupflicht?", "Wir führen den Winterdienst für Sie durch und dokumentieren die Einsätze auf Wunsch. Die Details zur Übertragung der Pflichten regeln wir im Vertrag."),
            ("Bieten Sie Winterdienst auch für Firmen an?", "Ja, wir räumen und streuen auch Firmengelände, Parkplätze und Zugänge zu Geschäftsräumen in München."),
        ],
    },
    {
        "slug": "grundreinigung",
        "datei": "grundreinigung-muenchen.html",
        "name": "Grundreinigung",
        "icon": "i-sparkle",
        "title": "Grundreinigung München – bei Umzug & nach Renovierung | CD Reinigungsservice",
        "description": "Grundreinigung in München: intensive Tiefenreinigung bei Ein- und Auszug, nach Renovierung oder für Büros und Praxen. Jetzt kostenloses Angebot anfragen.",
        "h1": "Grundreinigung in München",
        "lead": "Intensive Tiefenreinigung bei Ein- und Auszug, nach Renovierung oder einmal im Jahr.",
        "text": [
            "Manchmal reicht die normale Unterhaltsreinigung nicht aus: nach einer Renovierung, beim Ein- oder Auszug, vor der Übergabe einer Wohnung oder wenn sich über Monate hartnäckiger Schmutz angesammelt hat. Dann ist eine Grundreinigung die richtige Wahl. CD Reinigungsservice führt Grundreinigungen in München für Wohnungen, Häuser, Büros und Gewerberäume durch.",
            "Bei einer Grundreinigung reinigen wir gründlich und bis in die Ecken – auch dort, wo im Alltag selten geputzt wird. Dazu gehören Fußleisten, Türen und Zargen, Heizkörper, Steckdosen, Fliesen und Fugen, Küchenschränke innen und außen sowie Sanitärobjekte mit Kalkablagerungen. Auf Wunsch reinigen wir dabei auch die Fenster mit.",
            "Besonders gefragt ist die Grundreinigung bei einer Wohnungsübergabe in München. Eine saubere Übergabe vermeidet Diskussionen mit dem Vermieter und erleichtert die Rückgabe der Kaution. Auch nach Handwerkerarbeiten entfernen wir Baustaub, Farbspritzer und Rückstände, damit Sie Ihre Räume direkt nutzen können.",
            "Beschreiben Sie uns kurz die Räume, die Größe und den Anlass der Reinigung, gern auch mit Fotos per WhatsApp. Wir erstellen Ihnen ein individuelles Angebot und finden einen Termin, der zu Ihrem Umzug oder Ihrer Renovierung passt.",
        ],
        "warum": "Eine Grundreinigung braucht Zeit, Erfahrung und die richtigen Mittel für die verschiedenen Oberflächen. Wir prüfen vorher, welche Materialien verbaut sind, und reinigen so, dass nichts beschädigt wird – von empfindlichem Parkett bis zu stark verkalkten Duschen. Gerade bei Umzügen in München ist der Zeitplan oft knapp. Deshalb stimmen wir den Termin eng mit Ihrem Übergabetermin ab. Sie haben mit Inhaber Eric Darko einen festen Ansprechpartner, der für Rückfragen direkt erreichbar ist.",
        "umfang": [
            "Böden intensiv reinigen, inklusive Ecken und Fußleisten",
            "Türen, Zargen, Lichtschalter und Steckdosen",
            "Küche: Schränke innen und außen, Geräte, Fliesenspiegel",
            "Bad und WC: Entkalken von Armaturen, Fliesen und Fugen",
            "Heizkörper und Fensterbänke",
            "Entfernen von Baustaub und Renovierungsrückständen",
        ],
        "faq": [
            ("Was ist der Unterschied zwischen Grundreinigung und Unterhaltsreinigung?", "Die Unterhaltsreinigung findet regelmäßig statt und hält den Zustand sauber. Die Grundreinigung ist eine einmalige, intensive Tiefenreinigung, bei der auch hartnäckiger Schmutz und schwer erreichbare Stellen gereinigt werden."),
            ("Bieten Sie Endreinigung bei Auszug an?", "Ja, wir übernehmen die Endreinigung Ihrer Wohnung in München vor der Übergabe an den Vermieter oder Nachmieter."),
            ("Reinigen Sie auch nach Renovierungen?", "Ja, wir entfernen Baustaub, Farbspritzer und andere Rückstände nach Handwerkerarbeiten, damit Ihre Räume sofort nutzbar sind."),
            ("Wie schnell bekomme ich einen Termin?", "Melden Sie sich mit Ihrem Wunschtermin. Wir antworten innerhalb von 24 Stunden und versuchen, auch kurzfristige Termine möglich zu machen."),
        ],
    },
]
